[package]
name = "file_map_reduce"
version = "0.1.0"
authors = ["qingzhu <q15000557748@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.3.17"
clap = "2.32.0"
hashbrown = "0.2.0"
seahash = "3.0.5"